spring.application.name=server
server.port=${PORT:8080}

# Database URL
spring.datasource.url=JDBC:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:blog_webapp_db}

# DB credentials
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin@123}

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true